# Generated by Django 3.2.2 on 2021-05-28 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='contexte',
        ),
    ]
