# Generated by Django 3.2.2 on 2021-05-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_react_contexte'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='contexte',
            field=models.TextField(default='ok'),
            preserve_default=False,
        ),
    ]
