# Generated by Django 3.2.2 on 2021-05-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_react_contexte'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='contexte',
            field=models.TextField(blank=True),
        ),
    ]
